name: "Bug Report"
description: Report a bug in Blastr
title: "Bug: [Clear bug title]"
labels: ["Bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "Describe what went wrong. Be as specific as possible."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "What did you expect to happen?"
      description: "Describe the expected behavior or result."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to reproduce"
      description: |
        Provide the steps to reproduce the issue. Example:
        1. Go to `App.blast`
        2. Use `signal()` inside a component
        3. See that updates are not triggered
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment / Context"
      description: "Blastr version, browser, OS, and any relevant tech details."
    validations:
      required: false
