name: Epic
description: Planning a major feature
title: "EPIC: [Feature Name]"
labels: [epic]
body:
- type: Markdown
attributes:
value: |
An epic is a key feature to be broken down into several subtasks (issues).
- type: Textarea
id: Objective
attributes:
label: Objective of the epic
description: What should this feature accomplish?
- type: Textarea
id: Tasks
attributes:
label: Subtasks
description: List of related issues (create them later if needed).
value: |
- [ ] #Issue1
- [ ] #Issue2
