name: Epic
description: Planification d'une fonctionnalité majeure
title: "EPIC: [Nom de la feature]"
labels: [epic]
body:
  - type: markdown
    attributes:
      value: |
        Une *epic* est une fonctionnalité clé à découper en plusieurs sous-tâches (issues).
  - type: textarea
    id: objectif
    attributes:
      label: Objectif de l'epic
      description: Que doit accomplir cette fonctionnalité ?
  - type: textarea
    id: tasks
    attributes:
      label: Sous-tâches
      description: Liste des issues liées (crée-les ensuite si besoin).
      value: |
        - [ ] #Issue1
        - [ ] #Issue2
