name: "New Feature"
description: Suggest a new idea
title: "Feature: [Title]"
labels: ["Feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "Décris en détail la fonctionnalité que tu proposes."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Technical Solution"
      description: "Si tu as déjà une idée d'implémentation technique, note-la ici."
    validations:
      required: false
